"use client";

import { cn } from '@/lib/utils';
import {
    ArrowDownRight,
    ArrowUpRight,
    CheckCircle,
    Download,
    Loader2,
    Plus
} from 'lucide-react';
import Link from 'next/link';
import { useEffect, useState } from 'react';

export default function DashboardPage() {
  const [data, setData] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function fetchStats() {
      try {
        const res = await fetch('/api/stats');
        const json = await res.json();
        setData(json);
      } catch (error) {
        console.error("Failed to fetch dashboard stats", error);
      } finally {
        setLoading(false);
      }
    }
    fetchStats();
  }, []);

  if (loading) return (
    <div className="flex items-center justify-center min-h-[400px]">
      <Loader2 className="animate-spin text-primary" size={40} />
    </div>
  );

  const { stats, recentActivity, categories } = data;

  const handleExportReport = async () => {
    try {
      // Fetch detailed data for the report
      const [assetsRes, assignmentsRes] = await Promise.all([
        fetch('/api/assets'),
        fetch('/api/assignments')
      ]);
      const assets = await assetsRes.json();
      const assignments = await assignmentsRes.json();
      
      const printWindow = window.open('', '_blank');
      if (!printWindow) return;

      const html = `
        <!DOCTYPE html>
        <html>
        <head>
          <title>APMS Detailed Report - ${new Date().toLocaleDateString()}</title>
          <style>
            body { font-family: sans-serif; padding: 20px; color: #333; }
            h1 { text-align: center; border-bottom: 2px solid #333; padding-bottom: 10px; margin-bottom: 20px; }
            .meta { margin-bottom: 30px; font-size: 14px; color: #666; }
            .section { margin-bottom: 40px; }
            h2 { font-size: 18px; border-bottom: 1px solid #ccc; padding-bottom: 5px; margin-bottom: 15px; }
            table { width: 100%; border-collapse: collapse; font-size: 12px; }
            th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
            th { background-color: #f4f4f4; font-weight: bold; }
            .stats-grid { display: flex; gap: 20px; margin-bottom: 30px; }
            .stat-box { border: 1px solid #ccc; padding: 15px; flex: 1; text-align: center; border-radius: 4px; }
            .stat-value { font-size: 24px; font-weight: bold; display: block; margin-top: 5px; }
            .footer { text-align: center; margin-top: 50px; font-size: 10px; color: #999; border-top: 1px solid #eee; padding-top: 20px; }
          </style>
        </head>
        <body>
          <h1>Asset & Property Management System Report</h1>
          <div class="meta">
            Generated on: ${new Date().toLocaleString()}<br>
            Generated by: Admin User
          </div>

          <div class="section">
            <div class="stats-grid">
              ${stats.map((s: any) => `
                <div class="stat-box">
                  <div class="stat-label">${s.label}</div>
                  <div class="stat-value">${s.value}</div>
                </div>
              `).join('')}
            </div>
          </div>

          <div class="section">
            <h2>Current Asset Inventory</h2>
            <table>
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Category</th>
                  <th>Serial Number</th>
                  <th>Location</th>
                  <th>Condition</th>
                  <th>Quantity (Avail/Total)</th>
                </tr>
              </thead>
              <tbody>
                ${assets.map((a: any) => `
                  <tr>
                    <td>${a.name}</td>
                    <td>${a.category}</td>
                    <td>${a.serialNumber || 'N/A'}</td>
                    <td>${a.location}</td>
                    <td>${a.condition}</td>
                    <td>${a.quantity.available} / ${a.quantity.total}</td>
                  </tr>
                `).join('')}
              </tbody>
            </table>
          </div>

          <div class="section">
            <h2>Recent Assignments</h2>
            <table>
              <thead>
                <tr>
                  <th>Asset</th>
                  <th>Assignee</th>
                  <th>Type</th>
                  <th>Date Assigned</th>
                  <th>Status</th>
                </tr>
              </thead>
              <tbody>
                ${assignments.slice(0, 20).map((a: any) => `
                  <tr>
                    <td>${a.asset?.name || 'Deleted Asset'}</td>
                    <td>${a.assignee.name}</td>
                    <td>${a.assignee.type}</td>
                    <td>${new Date(a.assignedDate).toLocaleDateString()}</td>
                    <td>${a.status}</td>
                  </tr>
                `).join('')}
              </tbody>
            </table>
          </div>

          <div class="footer">
             CONFIDENTIAL - internal use only. Generated by APMS.
          </div>
          <script>
            window.onload = () => { window.print(); }
          </script>
        </body>
        </html>
      `;

      printWindow.document.write(html);
      printWindow.document.close();
    } catch (error) {
      console.error("Export failed", error);
      alert("Failed to export report. Please try again.");
    }
  };

  return (
    <div className="space-y-8 animate-in fade-in duration-500">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold tracking-tight">Dashboard Overview</h2>
          <p className="text-sm text-muted-foreground">Monitor your assets and recent assignments.</p>
        </div>
        <div className="flex gap-2">
          <button 
            onClick={handleExportReport}
            className="btn btn-secondary text-sm flex items-center gap-2"
          >
            <Download size={14} /> Export Report
          </button>
          <Link href="/assets" className="btn btn-primary text-sm flex items-center gap-2">
            <Plus size={14} /> Add Asset
          </Link>
        </div>
      </div>

      {/* Stats Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        {stats.map((stat: any) => (
          <div key={stat.label} className="card p-5 group hover:border-primary/30 transition-all duration-300">
            <div className="flex items-start justify-between">
              <div>
                <p className="text-xs font-bold uppercase text-muted-foreground tracking-wider">{stat.label}</p>
                <h3 className="text-3xl font-extrabold mt-1 group-hover:text-primary transition-colors">{stat.value}</h3>
              </div>
              <div className="text-2xl opacity-20 group-hover:opacity-100 group-hover:scale-110 transition-all duration-300">
                {stat.icon}
              </div>
            </div>
            <div className="mt-4 flex items-center gap-1.5 text-xs">
              {stat.change.startsWith('+') ? (
                <span className="flex items-center gap-0.5 text-green-600 font-bold bg-green-50 dark:bg-green-900/20 px-1.5 py-0.5 rounded">
                  <ArrowUpRight size={12} /> {stat.change}
                </span>
              ) : (
                <span className="flex items-center gap-0.5 text-red-600 font-bold bg-red-50 dark:bg-red-900/20 px-1.5 py-0.5 rounded">
                  <ArrowDownRight size={12} /> {stat.change}
                </span>
              )}
              <span className="text-muted-foreground">vs last period</span>
            </div>
          </div>
        ))}
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Recent Activity */}
        <div className="lg:col-span-2 card flex flex-col">
          <div className="p-4 border-b border-border flex items-center justify-between bg-secondary/10">
            <h3 className="font-bold flex items-center gap-2">
              <span className="w-1.5 h-6 bg-primary rounded-full"></span>
              Recent Activity
            </h3>
            <Link href="/assignments" className="text-primary text-xs font-bold hover:underline px-2 py-1 rounded hover:bg-primary/5 transition-colors">
              View All Assignments
            </Link>
          </div>
          <div className="p-4 space-y-1 flex-1">
            {recentActivity && recentActivity.length > 0 ? recentActivity.map((activity: any) => (
              <div key={activity.id} className="flex items-center justify-between text-sm p-3 rounded-lg hover:bg-secondary/40 transition-colors group">
                <div className="flex items-center gap-4">
                  <div className="w-10 h-10 rounded-xl bg-secondary flex items-center justify-center text-lg shadow-sm group-hover:shadow-md transition-all">
                    {activity.icon}
                  </div>
                  <div>
                    <p className="font-bold text-foreground leading-tight">{activity.title}</p>
                    <p className="text-xs text-muted-foreground mt-0.5">{activity.subtitle}</p>
                  </div>
                </div>
                <div className="text-[10px] font-extrabold px-2 py-1 rounded bg-secondary text-muted-foreground uppercase tracking-widest group-hover:bg-primary/10 group-hover:text-primary transition-colors">
                  {activity.type}
                </div>
              </div>
            )) : (
              <div className="flex flex-col items-center justify-center py-12 text-center text-muted-foreground opacity-50">
                 <CheckCircle size={40} className="mb-2" />
                 <p className="text-sm">No recent activity found.</p>
              </div>
            )}
          </div>
        </div>

        {/* Categories Breakdown */}
        <div className="card flex flex-col">
          <div className="p-4 border-b border-border bg-secondary/10">
            <h3 className="font-bold">By Category</h3>
          </div>
          <div className="p-6 space-y-6 flex-1">
            {categories && categories.length > 0 ? categories.map((cat: any) => (
              <div key={cat.label} className="space-y-2">
                <div className="flex justify-between text-xs font-bold uppercase tracking-wider">
                  <span className="text-muted-foreground">{cat.label}</span>
                  <span className="text-foreground">{cat.count} assets</span>
                </div>
                <div className="w-full h-2.5 bg-secondary rounded-full overflow-hidden shadow-inner">
                  <div 
                    className={cn(cat.color, "h-full rounded-full transition-all duration-1000 ease-out shadow-sm")} 
                    style={{ width: `${(cat.count / 100) * 100}%` }} // Simplified percentage
                  ></div>
                </div>
              </div>
            )) : (
              <p className="text-center text-sm text-muted-foreground italic py-10 leading-relaxed">
                Connect assets to see category distribution.
              </p>
            )}
          </div>
          <div className="p-4 bg-secondary/5 mt-auto border-t border-border">
             <div className="flex items-center justify-center gap-1.5 text-[10px] font-bold text-muted-foreground uppercase tracking-tighter">
                <CheckCircle size={10} className="text-green-500" />
                Updated minutes ago
             </div>
          </div>
        </div>
      </div>
    </div>
  );
}
